-- [ IV ]. DDL,DML,DCL
-- SQL의 종류
-- DCL 사용자 계정 생성(CREATE USER), 권한 부여 GRANT(SESSION, SESSION&SELECT, DBA 등), 권한 박탈(REVOKE), 사용자 계정 삭제(DROP USER),
--          트랜잭션 명령어
-- DDL : 테이블 생성(CREATE TABLE),  테이블 구조 변경(ALTER TABLE), 테이블 삭제(DROP TABLE)
-- DML : INSERT(C), SELECT(R), UPDATE(U), DELETE(D) - DML은 취소 가능(ROLLBACK)
----------------------------------------------------------------------------------------------------------------------------------------

-- ★ DDL
-- 1. 테이블 생성 (CREATE TABLE 테이블명...) : 테이블 구조를 정의한다.
CREATE TABLE BOOK(
    BOOKID NUMBER(4), -- BOOK 필드의 타입은 숫자 4자리, 제약 조건 PRIMARY KEY, NOT NULL, UNIQUE
    BOOKNAME VARCHAR2(20), -- BOOKNAME 필드의 타입은 문자 20BYTE
    PUBLISHER VARCHAR2(20), -- PUBLISHER 필드의 타입은 문자 20BYTE
    RDATE DATE, -- RDATE 필드의 타입은 DATE
    PRICE NUMBER(8,2), -- PRICE의 필드 타입은 숫자 전체 8 자리 중 소수점 2자리
     PRIMARY KEY(BOOKID)
);

SELECT * FROM BOOK;
DESC BOOK;

DROP TABLE BOOK; -- 2. 테이블 삭제
CREATE TABLE BOOK(
    BOOKID NUMBER(4) PRIMARY KEY,
    BOOKNAME VARCHAR2(20),
    PUBLISHER VARCHAR2(20),
    RDATE DATE,
    PRICE NUMBER(8,2)
);
DESC BOOK;
-- EX. DEPT01 (DEPTNO NUMBER(2) PRIMARY KEY, DNAME VARCHAR2(14), LOC VARCHAR2(13))
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY, 
    DNAME VARCHAR2(14), 
    LOC VARCHAR2(13)
);
DESC DEPT01;
SELECT * FROM DEPT01;

SELECT * FROM DEPT; -- 10,20,30,40
SELECT DISTINCT DEPTNO FROM EMP; -- 10,20,30
DESC EMP;

INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (9999,'HONG',40);
SELECT * FROM EMP;
INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (9998,'KONG',50); -- ERROR : DEPT 테이블의 DEPTNO를 참조하기 때문에 DEPT에 없는 50은 입력 불가

DESC DEPT;
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (50,'REST','SEOUL');
ROLLBACK; -- DML 취소 트랜잭션 명령어 : COMMIT 안한 모든 DML을 초기화
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT * FROM DEPT01;
-- EMP 테이블 과 유사한 EMP01 테이블 
CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR(10),
    SAL NUMBER(7,2),
    DEPTNO NUMBER(2) REFERENCES DEPT01(DEPTNO) -- FOREIGN KEY 제약 조건 설정
);
DROP TABLE EMP001; -- 테이블 삭제

-- FK, PK를 아래로 작성하여 TABLE 생성
CREATE TABLE EMP001(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    SAL NUMBER(7,2),
    DEPTNO NUMBER(2),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(DEPTNO) REFERENCES DEPT01(DEPTNO) -- DEPT01 : PARENT TABLE / DEPTNO : PARENT KEY
);
SELECT * FROM EMP01;

-- ★ DML
    -- 1. INSERT
        -- 1) INSERT INTO 테이블명 (필드명들.....) VALUES (값들....); => 필드명의 개수와 값의 개수가 동일해야한다
        -- 2) INSERT INTO 테이블명 VALUES (값1, 값2, .... 값N);
SELECT * FROM DEPT01;
SELECT * FROM EMP001;
SELECT * FROM BOOK;
-- EMP001의 DEPTNO는 DEPT01을 참조하기 때문에 현재 절대 입력 불가. 이 때, DEPT01 을 PARENT DB라 칭한다.
INSERT INTO DEPT01 VALUES(50, 'ACCOUNTING','SEOUL');
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC) VALUES(51, '전산','신림');
INSERT INTO DEPT01 (DNAME, LOC, DEPTNO) VALUES('영업','봉천',52);
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC) VALUES(53, '연구',NULL); -- 명시적으로 NULL을 입력
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES(60, '설계'); -- 묵시적으로 NULL 입력
COMMIT; -- 트랜잭션 영역에 쌓여있는 DML명령어 일괄 실행
SELECT * FROM EMP001;
-- 서브쿼리를 이용한 INSERT
    -- EX. DEPT테이블에서 10~30 부서의 내용을 DEPT01 테이블에 INSERT
    INSERT INTO DEPT01 SELECT * FROM DEPT WHERE DEPTNO<40;
SELECT * FROM DEPT01;

-- 2. UPDATE 테이블이름 SET 필드명1=적용할내용1[, 필드명2=적용할내용2,...] [WHERE 조건];
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP; -- 서브쿼리를 통한 테이블 복사
SELECT * FROM EMP01;
    -- EX1. 부서번호를 30으로 수정
    UPDATE EMP01 SET DEPTNO=30;
    ROLLBACK; -- DML만 취소
    -- EX2. 모든 사원에 대해서 급여를 10% 인상해라
    UPDATE EMP01 SET SAL=SAL*1.1;
    ROLLBACK;
    -- EX3. EMP01에서 10번 부서 직원을30번 부서로
    UPDATE EMP01 SET DEPTNO=30 WHERE DEPTNO=10;
    SELECT DISTINCT DEPTNO FROM EMP01;
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
SELECT * FROM EMP01;
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD'; -- 날짜 포멧 변경 방법    
    -- EX4. SCOTT의 부서번호를 30, JOB은 'MANAGER'로, SAL과 COMM을 500 인상, 입사일은 오늘로, MGR을 KING으로
    UPDATE EMP01 
        SET 
            DEPTNO=30, 
            JOB='MANAGER', 
            SAL = SAL+500, 
            COMM = NVL(COMM,0) + 500, 
            -- HIREDATE = TO_DATE('25/06/04','YY/MM/DD')
            HIREDATE = SYSDATE,
            MGR = (SELECT EMPNO FROM EMP01 WHERE ENAME='KING')
        WHERE
            ENAME = 'SCOTT';
        -- EX5. DALLAS에 근무하는 직원의 급여와 상여를 100만큼 인상
        UPDATE EMP01 
            SET SAL = SAL+500, 
                    COMM = NVL(COMM,0)+500
            WHERE 
                DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
        SELECT * FROM EMP01 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
        -- EX6. EMP01에서 모든 사원의 급여와 입사일을 'KING'의 급여와 입사일로 수정
        UPDATE EMP01
            SET SAL = (SELECT SAL FROM EMP01 WHERE ENAME='KING'),
                    HIREDATE = (SELECT HIREDATE FROM EMP01 WHERE ENAME='KING');
        SELECT * FROM EMP01;
        ROLLBACK;
        
-- 3. DELETE FROM 테이블명 [WHERE 조건];
DELETE FROM EMP01;
SELECT * FROM EMP01;
ROLLBACK; -- INSERT, UPDATE, DELETE만 취소 가능
DELETE FROM DEPT; -- 불가. EMP가 DEPT의 DEPTNO를 참조중.
    -- EX1. EMP01에서 'FORD'직원을 퇴사
    DELETE FROM EMP01 WHERE ENAME='FORD';
    -- EX2. EMP01에서 30번 부서 직원 삭제  
    DELETE FROM EMP01 WHERE DEPTNO = 30;
    -- EX3. 부서명이 RESEARCH 부서인 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='RESEARCH');
    ROLLBACK;
    -- SAM01 : JOB이 없는 사원 삭제
    DELETE FROM SAM01 WHERE JOB IS NULL;
    SELECT * FROM SAM01;
    -- SAM01 : 이름이 ORANGE 삭제
    DELETE FROM SAM01 WHERE ENAME = 'ORANGE';
    SELECT * FROM SAM01;

SELECT * FROM EMP;
SELECT * FROM DEPT;

--  ★ 제약조건의 종류 : INSERT, UPDATE를 할 때, 제약조건에 맞는 데이터만 INSERT, UPDATE됨
    -- 1) PRIMARY KEY : 테이블의 각 행을 유일한 값으로 식별하기 위한 필드
    -- 2) FOREIGN KEY : 테이블의 열이 다른 테이블의 열을 참조
    -- 3) NOT NULL : NULL을 포함하지 않는 필드
    -- 4) UNIQUE : 모든 행의 값이 유일한 값. NULL 허용(NULL은 여러개 입력 가능)
    -- 5) CHECK(조건) : 해당 조건이 만족하는 지(NULL값 허용)
    -- DEFAULT 기본값 : 해당 열의 데이터를 입력하지 않으면 원래는 NULL이 들어갈 것을 기본값을 기입
    
-- DEPT1 & EMP1 (eXERD를 통해 ERD 작성(= 테이블 설계) -> DDL)
DROP TABLE DEPT1;
CREATE TABLE DEPT1(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14) NOT NULL,
    LOC VARCHAR2(13) NOT NULL,
    PRIMARY KEY(DEPTNO),
    UNIQUE(DNAME)
);
DROP TABLE EMP1;
CREATE TABLE EMP1(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2) ,
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
     PRIMARY KEY(EMPNO),
     CHECK(SAL>0),
     CHECK(COMM>=0),
     FOREIGN KEY(DEPTNO) REFERENCES DEPT1(DEPTNO)
);
DESC EMP1;
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL, DEPTNO)
                VALUES (1111,'HONG','MANAGER',1000,10); -- parent key not found 오류 발생 : DEPT1이 없어서 발생, FK

INSERT INTO DEPT1 SELECT * FROM DEPT; -- DEPT 내용을 DEPT1에 INSERT
INSERT INTO DEPT1 VALUES(40,'IT','SEOUL'); -- PK 원칙 에러 : UNIQUE
INSERT INTO DEPT1 (DNAME, LOC) VALUES ('IT','SEOUL'); -- PK 원칙 에러 : NOT NULL
SELECT * FROM DEPT1;
INSERT INTO DEPT1 VALUES (40,'SALES','SEOUL'); -- UNIQUE 에러
INSERT INTO DEPT1 (DEPTNO, DNAME) VALUES (50,'DATA'); -- NOT NULL 에러

INSERT INTO EMP1 (EMPNO, ENAME, JOB) VALUES (1001,'HONGGILDONG','MANAGER'); -- VARCHAR2 길이 에러
INSERT INTO EMP1 (EMPNO, ENAME, JOB) VALUES (1001,'HONG','MANAGER'); -- HIREDATE 에서 DEFAULT 적용
SELECT * FROM EMP1;
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES(1002,'KIM','MANAGER',0); -- CHECK 에러
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES(1002,'KIM','MANAGER',1);
SELECT * FROM EMP1;