-----------------------1번-----------------------
CREATE TABLE SAM01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2),
    PRIMARY KEY(EMPNO)
);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1000,'APPLE','POLICE',10000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1010,'BANANA','NURSE',15000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1020,'ORANGE','DOCTOR',25000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1030,'VERY',NULL,25000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1040,'CAT',NULL,2000);
SELECT * FROM SAM01;
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE ENAME IN ('CLARK', 'KING', 'MILLER');
SELECT * FROM SAM01;

-----------------------2번-----------------------
-- 1. 데이터 구조 생성
CREATE TABLE MY_DATA(
ID NUMBER(4),
NAME VARCHAR2(10),
USERID VARCHAR(30),
SALARY NUMBER(10, 2),
PRIMARY KEY(ID));

-- 2. 데이터 값 지정
INSERT INTO MY_DATA VALUES (1, 'SCOTT', 'SSCOTT', 10000.00);
INSERT INTO MY_DATA VALUES (2, 'FORD', 'FFORD', 13000.00);
INSERT INTO MY_DATA VALUES (3, 'PATEL', 'PPATEL', 33000.00);
INSERT INTO MY_DATA VALUES (4, 'REPORT', 'RREPORT', 23500.00);
INSERT INTO MY_DATA VALUES (5, 'GOOD', 'GGOOD', 44450.00);
SELECT * FROM MY_DATA;

-- 3. TO_CHAR 내장함수를 이용하여 입력한 자료를 도표와 같은 형식으로 출력하는 SQL문을 작성하라
SELECT 
    ID,
    NAME,
    USERID, 
    TO_CHAR(SALARY, '9,999,999.00') AS SALARY_FORMATTED
FROM MY_DATA;

-- 4. 자료를 영구적으로 DB에 등록하는 명령어를 작성
COMMIT;
SELECT * FROM MY_DATA;

-- 5. ID가 3번인 사람의 급여를 65000.00 으로 갱신하고 영구적으로 DB에 반영
UPDATE MY_DATA  SET SALARY =65000.00 WHERE ID=3;
SELECT * FROM MY_DATA;
COMMIT;

--6. NAME이 FORD인 사람을 삭제하고 영구적으로 DB에 반영
DELETE FROM MY_DATA WHERE NAME='FORD';
SELECT * FROM MY_DATA;
COMMIT;

-- 7. SALARY가 15,000.00 이하인 사람의 급여를 15,000.00으로 변경하라
UPDATE MY_DATA SET SALARY = 15000.00 WHERE SALARY <=15000.00;
SELECT * FROM MY_DATA;

-- 8. MY_DATA를 삭제하라
DROP TABLE MY_DATA;

-----------------------3번-----------------------
DROP TABLE EMP01;
--1.
CREATE TABLE EMP01 AS SELECT * FROM EMP;
UPDATE EMP01 SET DEPTNO=30;
SELECT * FROM EMP01;
-- 2. 
UPDATE EMP01 SET SAL= SAL*1.1;
SELECT * FROM EMP01;
-- 3.
UPDATE EMP01 SET SAL = SAL*1.1 WHERE SAL>=3000;
SELECT * FROM EMP01;
-- 4.
UPDATE EMP01 SET SAL = SAL + 1000 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS'); -- DEPTNO를 1번 문제에서 30으로 수정하며 해당내용 없음
-- 5. 
UPDATE EMP01 SET DEPTNO=20, JOB = 'MANAGER' WHERE ENAME='SCOTT';
--6. 
DELETE EMP01 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES'); 
--7. 
DELETE EMP01 WHERE ENAME='FORD';
-- 8.
DELETE SAM01 WHERE JOB='NULL';
-- 9.
DELETE SAM01 WHERE ENAME = 'ORANGE';
-- 10. 
UPDATE SAM01 SET SAL=1500  WHERE SAL<=1500;
-- 11.
UPDATE SAM01 SET SAL = SAL * 1.1 WHERE JOB = 'MANAGER';

-----------------------4번-----------------------

CREATE TABLE MAJOR(
    mCODE NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(20),
    mOFFICE NUMBER(3)
);

INSERT INTO MAJOR VALUES (1,'컴퓨터공학',101);
INSERT INTO MAJOR VALUES (2,'빅데이터',102);
SELECT MCODE mCODE, MNAME mNAME, 'A'||MOFFICE||'호' MOFFICE FROM MAJOR;

CREATE TABLE STUDENT(
    SNO NUMBER(3) PRIMARY KEY,
    SNAME VARCHAR2(20),
    SSCORE NUMBER(3),
    MCODE NUMBER(2) REFERENCES MAJOR(MCODE)
);

INSERT INTO STUDENT VALUES (101,'홍길동',99,1);
INSERT INTO STUDENT VALUES (102,'신길동',100,2);

SELECT S.SNO 학번, S.SNAME 이름, S.SSCORE 점수, S.MCODE 학과코드, M.MNAME 학과명, 'A'||M.MOFFICE||'호' 학과사무실 
FROM STUDENT S, MAJOR M
WHERE S.MCODE = M.MCODE;
