-- 0 초기화
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
-- 1 생성
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
    
CREATE TABLE MEMBER(
    MNO NUMBER(5) PRIMARY KEY,
    MNAME VARCHAR2(50) NOT NULL,
    MPW VARCHAR2(8) NOT NULL,
    MEMAIL VARCHAR2(250) UNIQUE,
    MPOINT NUMBER(9) CHECK(MPOINT>=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);
-- 2. 값 대입
    -- 2-1. PARENT TABLE 우선 생성
    INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
    INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
    INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
    INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
    -- 2-2. CHILED TABLE 생성
    INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'홍길동','aa','hong@hong.com',0,TO_DATE('24/09/26','YY/MM/DD'),0);
    INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'신길동','bb','sin@sin.com',1000,TO_DATE('22/04/01','YY/MM/DD'),1);
SELECT * FROM MEMBER;

-- 3. 화면 출력
SELECT MNO, MNAME, TO_CHAR(MRDATE,'YYYY-MM-DD') MRDATE,MEMAIL,MPOINT POINT, LEVELNAME ||'고객' LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;
