-- [ V ]. Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도.
DROP SEQUENCE FREINDS_SEQ;
CREATE SEQUENCE FREINDS_SEQ 
    INCREMENT BY 1 -- 1씩 증가, 기본값 1
    START WITH 1 -- 1부터 시작, 기본값 1
    MAXVALUE 9999 -- 최대 9999까지 ★
    MINVALUE 1 -- 최소값
    NOCYCLE -- CYCLE/NOCYCLE : 순차번호를 반복시키거나 안시키거나 ★
    NOCACHE; -- 순차번호를 미리 만들어두지 않고 사용할 때마다 생성 ★
SELECT FREINDS_SEQ.NEXTVAL FROM DUAL; -- DUAL: 오라클에서 제공하는 테이블. 더미데이터로 SEQUENCE의 다음 값을 확인하는 등의 행위에 사용
SELECT FREINDS_SEQ.CURRVAL FROM DUAL;

DROP TABLE FRIENDS;
CREATE TABLE FRIENDS(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAST_MODIFIED DATE DEFAULT SYSDATE
);
DROP SEQUENCE FREINDS_SEQ;
CREATE SEQUENCE FREINDS_SEQ 
    MAXVALUE 99999 
    NOCYCLE NOCACHE;
    
INSERT INTO FRIENDS (NO,NAME,TEL,ADDRESS) VALUES(FREINDS_SEQ.NEXTVAL, '홍길동',NULL,'서울시 관악구 신림동');
INSERT INTO FRIENDS (NO,NAME,TEL,ADDRESS) VALUES(FREINDS_SEQ.NEXTVAL, '홍길동','010-9999-9999','서울시 관악구 신림동');
SELECT * FROM FRIENDS;