# Generated by Django 5.2.5 on 2025-08-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-id"]},
        ),
    ]
