# Generated by Django 5.2.5 on 2025-08-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-id"]},
        ),
    ]
